language: c

sudo: false

cache:
  directories:
    - ~/.stack
    - ~/.local

env:
  global:
    - ENCRYPTION_LABEL: 781a8c02ab27
    - DEPLOY_USER_EMAIL: travisci@example.com

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.3

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar -xzO --wildcards '*/stack' > ~/.local/bin/stack
  - chmod a+x ~/.local/bin/stack

install:
  - stack setup --no-terminal

script:
  - stack test --no-terminal --skip-ghc-check
  - stack sdist --no-terminal --skip-ghc-check

deploy:
  provider: script
  script: deploy.sh
  skip_cleanup: true
  on:
    branch: master
