language: c

sudo: false

cache:
  directories:
    - ~/.stack
    - ~/.local

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.2

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar -xzO --wildcards '*/stack' > ~/.local/bin/stack
  - chmod a+x ~/.local/bin/stack

install:
  - stack setup --no-terminal

script:
  - stack test --no-terminal --skip-ghc-check
